apiVersion: v1
kind: Pod
metadata:
  name: gama-api
  labels:
    app: gama-api
spec:
    containers:
    - name: gama-api
      image: rflpazini/jenkins-node-sample:latest
      ports:
      - containerPort: 3000
